env:
  browser: true
  commonjs: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
globals:
  WK_DEBUG: readonly
  WK_PRE: readonly
  TransformStream: readonly
rules: {}
